# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 17:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('father_name', models.CharField(default=None, max_length=50)),
                ('date_of_birth', models.CharField(default=None, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=10)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('office_address', models.CharField(default=None, max_length=10000)),
                ('mobile_number', models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('office_landline', models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('State_BAR_Registration', models.CharField(default=None, max_length=20)),
                ('local_BAR', models.CharField(default=None, max_length=20)),
                ('Place_Of_Practice', models.CharField(default=None, max_length=100)),
                ('area', multiselectfield.db.fields.MultiSelectField(choices=[('CIVIL', 'Civil Matters'), ('CRIMINAL', 'Criminal Matters'), ('FAMILY', 'Family Disputes Matters '), ('LABOUR', 'Labour Disputes Matters'), ('FOREST', 'Forest Matters'), ('ROC', 'Company Matters'), ('CONSUMER', 'Consumer Matters'), ('EXCISE', 'Excise Matters'), ('ELECTRICITY', 'Electricity Board Matters'), ('EPF', 'Employee Provident Fund'), ('RAILWAY', 'railway Matters'), ('PENSION', 'Pension Matters'), ('INCOME', 'Income Tax Matters'), ('WRITS', 'Writs')], default=None, max_length=100)),
                ('other_area', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Heads')),
            ],
        ),
    ]
