# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='defination',
            field=models.TextField(),
        ),
    ]
