# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20170331_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='single',
            name='documents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='single',
            name='faqs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='single',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='single',
            name='limitations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='single',
            name='procedure',
            field=models.TextField(),
        ),
    ]
