# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
