# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20170411_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralegalcontact',
            name='case',
            field=models.CharField(choices=[('AA', 'AA'), ('AC', 'AC'), ('AR', 'AR'), ('ARBA', 'ARBA'), ('ARBC', 'ARBC'), ('CEA', 'CEA'), ('CER', 'CER'), ('CESR', 'CESR'), ('COMA', 'COMA'), ('COMP', 'COMP'), ('COMPA', 'COMPA'), ('CONA', 'CONA'), ('CONC', 'CONC'), ('CONCR', 'CONCR'), ('CONT', 'CONT'), ('CONTR', 'CONTR'), ('CR', 'CR'), ('CRA', 'CRA'), ('CRR', 'CRR'), ('CRRE', 'CRRE'), ('CRRF', 'CRRF'), ('CRRFC', 'CRRFC'), ('CS', 'CS'), ('EP', 'EP'), ('FA', 'FA'), ('FEMA', 'FEMA'), ('ITA', 'ITA'), ('ITR', 'ITR'), ('LPA', 'LPA'), ('MA', 'MA'), ('MACE', 'MACE'), ('MACOM', 'MACOM'), ('MACTR', 'MACTR'), ('MAIT', 'MAIT'), ('MAVAT', 'MAVAT'), ('MCC', 'MCC'), ('MCOMA', 'MCOMA'), ('MCP', 'MCP'), ('MCRC', 'MCRC'), ('MCRP', 'MCRP'), ('MP', 'MP'), ('MWP', 'MWP'), ('OTA', 'OTA'), ('RP', 'RP'), ('SA', 'SA'), ('STR', 'STR'), ('TR', 'TR'), ('VATA', 'VATA'), ('WA', 'WA'), ('WP', 'WP'), ('WPS', 'WPS'), ('WTA', 'WTA'), ('WTR', 'WTR')], default=None, max_length=100),
        ),
    ]
